backstage:
  upstream:
    backstage:
      appConfig:
        aws:
          accounts:
            - accountId: techdocs
              accessKeyId: ${TECHDOCS_AWSS3_ACCESS_KEY_ID_CREDENTIAL}
              secretAccessKey: ${TECHDOCS_AWSS3_SECRET_ACCESS_KEY_CREDENTIAL}
        techdocs:
          publisher:
            type: awsS3
            awsS3:
              bucketName: rhdh-techdocs
              s3ForcePathStyle: true
              endpoint: https://${AWS_S3_ENDPOINT}
              region: us-east-1
              accountId: techdocs