app:
  title: 'Demo Developer Hub'
  branding:
    fullLogo: "data:image/svg+xml;base64,{{ .Files.Get "logo/logo.svg" | b64enc }}"
    fullLogoWidth: 90px

backend:
  baseUrl: ${RHDH_URL}
  cors:
      origin: ${RHDH_URL}
  csp:
      connect-src:
      - '''self'''
      - 'http:'
      - 'https:'
      img-src:
      - '''self'''
      - 'data:'
      - https://test-homepage.cluster-5clzf.5clzf.sandbox2839.opentlc.com

#catalog:
#  orphanStrategy: delete
#  rules:
#    - allow: [Component, System, API, Template, Location, Resource, User, Group, Domain]

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

# Allowed Hosts
reading:
  allow:
    - host: '*.'

auditLog:
  rotateFile:
    enabled: true
    logFileDirPath: /var/log/rhdh/audits
    logFileName: rhdh-audit-log-%DATE%.log
    frequency: '1d'
    dateFormat: 'YYYY-MM-DD'
    utc: false
    maxSize: 100m
    maxFilesOrDays: 365
    zippedArchive: false