{{- range $path, $bytes := .Files.Glob "app-configs/*.yaml" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs-{{ $path | base | replace ".yaml" "" | replace "app-configs/" "" | trunc 63 | trimSuffix "-" }}
data:
  {{ $path | replace "s/" "-" }}: |-
   {{- $bytes | toString | nindent 4 }} 
---
{{- end }}